Playground: Add chromium support
modmark-org/modmark pull request #151
Opened 2023-03-10 15:09 UTC by adelhult

Resolves GH-45. This PR adds support for the playground in Chromium browsers. This is done by instantiating the WASM module that contains the compiler inside of a web worker instead of the main thread.

2023-03-10 15:21 UTC, CMDJojo commented
Nice! Good job on the fix! However, I think we should change to import the script using ECMAScript module syntax since it looks cleaner, doesn't pollute the scope with stuff we don't know about, and have cleaner syntax overall when calling the functions. Firefox will support it in [version 111](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687), which is released [March 14th](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/111). This won't require changes to `wasm-pack` and so on, and is generally the preferred way to do it!

2023-03-10 15:25 UTC, CMDJojo commented
Also, this does not work...I think you failed to commit the `--no-modules` hack to get around ES module syntax. Doesn't run on FF110.0.1 on Windows 21H2

2023-03-10 15:26 UTC, adelhult commented
Yeah, noticed that too, forced push a change a few seconds ago.

2023-03-10 15:29 UTC, adelhult commented
> Nice! Good job on the fix! However, I think we should change to import the script using ECMAScript module syntax since it looks cleaner, doesn't pollute the scope with stuff we don't know about, and have cleaner syntax overall when calling the functions. Firefox will support it in [version 111](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687), which is released [March 14th](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/111). This won't require changes to `wasm-pack` and so on, and is generally the preferred way to do it!

Opened #152!

2023-03-10 15:39 UTC, CMDJojo commented
<img width="966" alt="image" src="https://user-images.githubusercontent.com/25929684/224358636-b84a18af-835c-4a63-a68b-7b133f7695fa.png">
I would love it if you made it render on load again as it did before, as it is a nice welcoming screen when the example document gets loaded

2023-03-10 15:41 UTC, adelhult commented
Hmm, I thought I fixed that again. Will take a look!

2023-03-10 15:54 UTC, CMDJojo requested changes

2023-03-10 15:54 UTC, CMDJojo commented on playground/static/main.js
> +                debugEditor.setValue(await compilerAction({ type: "ast", source: input }));
This is probably wrong, it seems strange to do the action type `ast` on both `ast-debug` and `ast` arms, probably a typo. See line 239.

2023-03-12 15:45 UTC, CMDJojo commented
![image](https://user-images.githubusercontent.com/25929684/224555777-f0a0f198-25a6-424b-9899-5d492f0dd492.png)
I still get the same problem sometimes, I think we still have a race condition between the document fetch and the parser/core loading, possibly... It would be nice to get this resolved before pushing something that works sometimes. (FF110.0.1 on Windows 21H2)

2023-03-12 15:47 UTC, CMDJojo commented
We might be able to solve this by fetching/displaying the welcome document strictly after we have loaded the core wasm, by sending an init event to the main (sync) JS. Or let the worker fetch the document itself

2023-03-12 18:58 UTC, CMDJojo commented
It seems like your last commit solved the problem. I think we are ready to merge it, but we should PR #152 asap to merge it on tuesday when the Firefox update goes stable and we can verify that ES modules work there as well! (Approved)

2023-03-12 18:58 UTC, CMDJojo approved these changes

2023-03-12 18:59 UTC, merged